apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: endpoints.wso2.com
  namespace: wso2
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: wso2.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1beta1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                service:
                  type: string
                port:
                  type: integer
                endpointType:
                  type: string
                http2Enabled:
                  type: boolean
                certificateName:
                  type: string
                timeout:
                  type: integer
                credentials:
                  type: object
                  properties:
                    type:
                      type: string
                    secret:
                      type: string
                    userName:
                      type: string
                    password:
                      type: string
                retryConfig:
                  type: object
                  properties:
                    count:
                      type: integer
                    statusCode:
                      type: integer
                circuitBreakers:
                  type: object
                  properties:
                    maxConnections:
                      type: integer
                    maxRequests:
                      type: integer
                    maxPendingRequests:
                      type: integer
                    maxRetries:
                      type: integer
                    maxConnectionPools:
                      type: integer
                loadBalanceEndpoints:
                  type: array
                  items:
                    type: object
                    properties:
                      service:
                        type: string
                      port:
                        type: integer
                failoverEndpoints:
                  type: array
                  items:
                    type: object
                    properties:
                      service:
                        type: string
                      port:
                        type: integer         
                 
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: endpoints
    # singular name to be used as an alias on the CLI and for display
    singular: endpoint
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: EndPoint
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - ep


  
  