apiVersion: wso2.com/v1beta1
kind: Policy
metadata:
  name: custom-policy-6
  namespace: wso2
spec:
  type: CALL_INTERCEPTOR_SERVICE
  parameters:
    - parameterName: interceptorServiceURL
      parameterValue: interceptor-svc
    - parameterName: includes
      parameterValue: this require a comma separated string, which describes what should be included in the request body of the interceptor service