apiVersion: wso2.com/v1beta1
kind: Policy
metadata:
  name: custom-policy-1
  namespace: wso2
spec:
  type: CUSTOM_POLICY_1
  parameters:
    - parameterName: x-wso2-custom-header
      parameterValue: foo
  policySpec:
    json:
      foo: fooVal
      bar: barVal
      baz:
        baz1: baz1
        baz2:
          foobaz: foobaz
          foobar: foobar
  template: |
    custom policy template starts here
      define custom policy here
    custom policy template ends here