apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: policies.wso2.com
  namespace: wso2
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: wso2.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1beta1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                type:
                  type: string
                parameters:
                  type: array
                  items:
                    type: object
                    properties:
                      parameterName:
                        type: string
                      parameterValue:
                        type: string
                policySpec:
                  type: object
                  properties:
                    json:
                      x-kubernetes-preserve-unknown-fields: true
                      type: object
                      description: this is arbitrary JSON
                template:
                  type: string

  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: policies
    # singular name to be used as an alias on the CLI and for display
    singular: policy
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Policy
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - pc



