apiVersion: wso2.com/v1beta1
kind: Policy
metadata:
  name: custom-policy-1
  namespace: wso2
spec:
  type: SET_HEADER
  parameters:
    - parameterName: x-wso2-custom-header
      parameterValue: foo



